#!/bin/bash

operation=$1

# check for no arguments
if [ "$*" == "" ] ; then
  echo "No arguments provided, use angular help for options"
  exit 1
fi

# at the moment all comands require two args so check it here
if [ $# -lt 2 ] ; then
  echo "At least two arguments are expected"
  exit 1
fi

# list the help options
if [ $operation == "help" ] ; then
  echo "help docs not yet implemented warte bitte"
  # create the help options later
  exit 1
fi

scriptPath=$(dirname $0)/angular

# get the libs
source $(dirname $0)/util/loader.sh
source $(dirname $0)/angular/scripts/loader.sh

# create a new project
if [ $operation == "new" ] ; then
  createProject $2
# cerate a new module, inside an existing project
elif [ $operation == 'module' ] ; then
  createModule $2
elif [ $operation == 'directive' ] ; then
  createDirective $2
elif [ $operation == 'service' ] ; then
  createService $2
elif [ $operation == 'factory' ] ; then
  createFactory $2
elif [ $operation == 'constant' ] ; then
  createConstant $2
elif [ $operation == 'value' ] ; then
  createValue $2
else
  echo "Unknown command, please use ang help for more info on usage"
  exit 1
fi
