#!/bin/bash
source $(dirname $0)/clark_scripts/loader.sh

operation=$1

if [ $operation == "ticket" ] ; then
  cd ~/Development/application
  bundle exec rake app:branch:ticket[$2]
elif [ $operation == "integration" ] ; then
  cd ~/Development/application
  bundle exec rake app:branch:integration[$2]
elif [ $operation == "release" ] ; then
  cd ~/Development/application
  bundle exec rake app:release
elif [ $operation == 'importProd' ] ; then
  importProd
elif [ $operation == 'client-setup' ] ; then
  cd ~/Development/application/client
  rm -rf node_modules bower_components dist tmp
  npm cache clean && bower cache clean
  npm install && bower install
fi
